# Visualizacao dos Outputs da Entrega 2 Revisada

Este notebook serve para gerar evidencias visuais da base antes e depois das transformacoes pedidas na reabertura da Entrega 2.

Ele le os arquivos gerados em `outputs/`, mostra amostras com `head(20)` e exibe os parametros salvos no metadata, principalmente os parametros da normalizacao.

## 1. Carregamento dos Arquivos

In [11]:
from pathlib import Path
import json

import pandas as pd

pd.set_option('display.max_columns', 120)
pd.set_option('display.width', 160)
pd.set_option('display.max_colwidth', 80)

current_dir = Path.cwd()
project_dir = current_dir.parent if current_dir.name == 'notebooks' else current_dir
output_dir = project_dir / 'outputs'

cleaned_path = output_dir / 'drug_events_cleaned.csv'
train_path = output_dir / 'drug_events_train_transformed.csv'
test_path = output_dir / 'drug_events_test_transformed.csv'
sample_path = output_dir / 'drug_events_sample.csv'
metadata_path = output_dir / 'data_preparation_metadata.json'

cleaned_df = pd.read_csv(cleaned_path)
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)
sample_df = pd.read_csv(sample_path)

with metadata_path.open(encoding='utf-8') as f:
    metadata = json.load(f)

print('Arquivos carregados:')
print(f'  Antes / base limpa: {cleaned_df.shape} -> {cleaned_path.name}')
print(f'  Depois / treino transformado: {train_df.shape} -> {train_path.name}')
print(f'  Depois / teste transformado: {test_df.shape} -> {test_path.name}')
print(f'  Amostra: {sample_df.shape} -> {sample_path.name}')
print(f'  Metadata: {metadata_path.name}')

Arquivos carregados:
  Antes / base limpa: (32309, 12) -> drug_events_cleaned.csv
  Depois / treino transformado: (22616, 17) -> drug_events_train_transformed.csv
  Depois / teste transformado: (9693, 17) -> drug_events_test_transformed.csv
  Amostra: (50, 18) -> drug_events_sample.csv
  Metadata: data_preparation_metadata.json

## 2. Dataset Antes das Novas Transformacoes

Este arquivo representa a base limpa vinda da primeira parte do trabalho. Ele ja possui os atributos selecionados, campos de medicamento agregados e a estrutura tabular final da Entrega 2 antiga.

In [12]:
cleaned_df.head(20)

,safetyreportid,serious,occurcountry,patient.drug.activesubstance.activesubstancename,patient.drug.drugcharacterization,patient.drug.medicinalproduct,patient.drug.count,patient.patientsex,patient.patientonsetage,patient.patientonsetageunit,patient.ageGroupCalculated,patient.ageGroupCalculated_was_imputed
0,24916426,1,NZ,ESTRADIOL,1,ESTRADIOL,1,female,52.0,801.0,adult,0
1,24917560,1,CA,CARBAMAZEPINE | CENOBAMATE | LAMOTRIGINE | OXCARBAZEPINE,1 | 2,CARBAMAZEPINE | LAMOTRIGINE | OXCARBAZEPINE | XCOPRI,12,unknown,NaN,NaN,adult,1
2,24917803,2,US,DUPILUMAB,1,DUPIXENT,2,male,63.0,801.0,elderly,0
3,24920814,1,FR,ACETAMINOPHEN | AMPHOTERICIN B | HEPARIN CALCIUM | LINEZOLID | MEROPENEM | O...,1 | 2,ACETAMINOPHEN | AMPHOTERICIN B | HEPARIN CALCIUM | LINEZOLID | MEROPENEM | O...,7,male,53.0,801.0,adult,0
4,24921071,1,AU,ACETAMINOPHEN | CLONIDINE HYDROCHLORIDE | DULOXETINE HYDROCHLORIDE | GABAPEN...,1,ACETAMINOPHEN | CLONIDINE HYDROCHLORIDE | DULOXETINE HYDROCHLORIDE | GABAPEN...,8,male,52.0,801.0,adult,0
5,24801764,1,FR,ACETAMINOPHEN | ATORVASTATIN CALCIUM\EZETIMIBE | CEMIPLIMAB-RWLC | CETUXIMAB...,1 | 2,CETUXIMAB | DOLIPRANE | DOXYCYCLINE | HERBALS\SAW PALMETTO | INDAPAMIDE\PERI...,12,male,89.0,801.0,elderly,0
6,24802789,2,US,TIRZEPATIDE,1,ZEPBOUND,3,female,33.0,801.0,adult,0
7,24802817,2,US,DUPILUMAB,1,DUPIXENT,1,female,50.0,801.0,adult,0
8,24804923,1,US,CEFTRIAXONE | METRONIDAZOLE,1 | 2,CEFTRIAXONE | METRONIDAZOLE,2,female,66.0,801.0,elderly,0
9,24921233,2,US,CETIRIZINE HYDROCHLORIDE,1,ZYRTEC,1,female,NaN,NaN,elderly,1
10,24921381,1,US,AZTREONAM LYSINE | VANCOMYCIN HYDROCHLORIDE,1 | 2,AZTREONAM LYSINE | VANCOMYCIN HYDROCHLORIDE,2,female,NaN,NaN,young_adult,1
11,24921853,1,GB,ACETAMINOPHEN | CALCIUM\CHOLECALCIFEROL | CODEINE | FAMOTIDINE | OMEPRAZOLE ...,1 | 2,ACETAMINOPHEN | CALCIUM\CHOLECALCIFEROL | CODEINE | FAMOTIDINE | OMEPRAZOLE ...,7,female,25.0,801.0,young_adult,0
12,24922797,1,FR,ACETAMINOPHEN | HERBALS\SAW PALMETTO | LAMOTRIGINE | RABEPRAZOLE SODIUM | RA...,1 | 2,DAFALGAN | HERBALS\SAW PALMETTO | LAMICTAL | RABEPRAZOLE SODIUM | RAMIPRIL |...,8,unknown,NaN,NaN,elderly,1
13,24922959,1,US,TAFAMIDIS,1,VYNDAMAX,1,unknown,NaN,NaN,adult,1
14,24923297,2,US,ACYCLOVIR | ALBUTEROL SULFATE | AZELAIC ACID | AZELASTINE HYDROCHLORIDE | BU...,1 | 2,ACYCLOVIR | ALBUTEROL SULFATE | AZELAIC ACID | AZELASTINE HYDROCHLORIDE | CL...,12,female,NaN,NaN,elderly,1
15,24923378,2,US,DUPILUMAB,1,DUPIXENT,1,female,5.0,801.0,child,0
16,24940983,2,US,ACETAMINOPHEN | AMBRISENTAN | CYANOCOBALAMIN | ERGOCALCIFEROL | IBUPROFEN | ...,1 | 2,AMBRISENTAN | IBUPROFEN | ORENITRAM | SILDENAFIL CITRATE | SOTATERCEPT | TYL...,11,male,NaN,NaN,elderly,1
17,24925174,2,US,ACETAMINOPHEN | APIXABAN | CABOZANTINIB S-MALATE | CHOLECALCIFEROL | DILTIAZ...,1 | 2,BENADRYL | CABOMETYX | CERTAVITE WITH ANTIOXIDANTS | DILTIAZEM | DOXYCYCLINE...,16,male,69.0,801.0,elderly,0
18,24927819,1,ES,CARBOPLATIN | CEFADROXIL | DEXAMETHASONE | PACLITAXEL,1,CARBOPLATIN | CEFADROXIL | DEXAMETHASONE | PACLITAXEL,4,male,64.0,801.0,elderly,0
19,24928171,1,US,DILTIAZEM HYDROCHLORIDE,1,DILTIAZEM HYDROCHLORIDE,2,female,NaN,NaN,elderly,1

## 3. Dataset Depois - Treinamento Transformado

Este arquivo e o conjunto de treinamento final. Ele ja passou pela divisao treino/teste, imputacao KNN sem vazamento, feature engineering e normalizacao.

In [13]:
train_df.head(20)

,safetyreportid,serious,occurcountry,patient.drug.activesubstance.activesubstancename,patient.drug.drugcharacterization,patient.drug.medicinalproduct,patient.drug.count,patient.patientsex,patient.patientonsetage,patient.patientonsetageunit,patient.ageGroupCalculated,patient.ageGroupCalculated_was_imputed,feature_n_active_substances,feature_n_drug_types,feature_has_medicinal_product,feature_multiple_drugs,feature_is_usa
0,23530731,1,IN,AMLODIPINE BESYLATE | AZATHIOPRINE | MYCOPHENOLATE MOFETIL | PREDNISOLONE | ...,1 | 2,AMLODIPINE | AZATHIOPRINE | MYCOPHENOLATE MOFETIL | PREDNISOLONE | TACROLIMUS,0.041753,female,NaN,NaN,young_adult,1,0.379624,1.371129,1,1,0
1,23573794,1,US,ALFUZOSIN | APIXABAN | BENAZEPRIL HYDROCHLORIDE | CARBIDOPA\LEVODOPA | HYDRO...,1 | 2,ALFUZOSIN | BENAZEPRIL | BENICAR | CARBIDOPA\LEVODOPA | ELIQUIS | HYDROCHLOR...,0.944776,male,76.0,801.0,elderly,0,1.936271,1.371129,1,1,1
2,24801725,1,US,GILTERITINIB | POSACONAZOLE,1,GILTERITINIB | POSACONAZOLE,-0.229154,female,70.0,801.0,elderly,0,-0.287511,-0.721418,1,1,1
3,24830941,1,US,ALPRAZOLAM | FENTANYL | OXYCODONE,1,ALPRAZOLAM | FENTANYL | OXYCODONE,-0.138851,male,30.0,801.0,adult,0,-0.065132,-0.721418,1,1,1
4,21927215,1,US,ATORVASTATIN CALCIUM | EMPAGLIFLOZIN | LISINOPRIL | TIRZEPATIDE,1 | 2,JARDIANCE | LIPITOR | LISINOPRIL | MOUNJARO | TOJEO,0.132055,male,44.0,801.0,adult,0,0.157246,1.371129,1,1,1
5,21883320,2,US,SACUBITRIL\VALSARTAN,1,ENTRESTO,-0.319456,female,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,1
6,23678680,2,US,DENOSUMAB,1,PROLIA,-0.319456,unknown,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,1
7,22084593,1,FR,ACETAMINOPHEN | ALPRAZOLAM | PROPRANOLOL HYDROCHLORIDE,1 | 2,ACETAMINOPHEN | ALPRAZOLAM | PROPRANOLOL,-0.138851,female,43.0,801.0,adult,0,-0.065132,1.371129,1,1,0
8,21800099,2,US,ABATACEPT,1,ORENCIA,-0.229154,female,72.0,801.0,elderly,0,-0.509889,-0.721418,1,1,1
9,23409935,1,AU,BORTEZOMIB,1,BORTEZOMIB,-0.319456,male,69.0,801.0,elderly,0,-0.509889,-0.721418,1,0,0
10,24854567,1,FR,GLIMEPIRIDE | METFORMIN HYDROCHLORIDE | SPIRONOLACTONE | VILDAGLIPTIN,1,GLIMEPIRIDE | METFORMIN | SPIRONOLACTONE | VILDAGLIPTIN,-0.048549,unknown,NaN,NaN,elderly,1,0.157246,-0.721418,1,1,0
11,23552895,1,US,AMANTADINE | AMPHETAMINE ASPARTATE\AMPHETAMINE ASPARTATE MONOHYDRATE\AMPHETA...,1 | 2,"AMANTADINE | DEXTROAMPHET SACCHARAT, AMPHET ASPARTATE, DEXTROAMPHET SULFATE ...",0.041753,unknown,NaN,NaN,elderly,1,0.157246,1.371129,1,1,1
12,23387999,1,GB,ALLOPURINOL | FINASTERIDE,1 | 2,ALLOPURINOL | FINASTERIDE,-0.229154,male,49.0,801.0,adult,0,-0.287511,1.371129,1,1,0
13,21168322,1,AU,VEDOLIZUMAB,1,VEDOLIZUMAB,-0.229154,male,NaN,NaN,adult,1,-0.509889,-0.721418,1,1,0
14,20524604,2,US,SILDENAFIL CITRATE | TREPROSTINIL,1 | 2,SILDENAFIL CITRATE | TREPROSTINIL,-0.138851,female,NaN,NaN,adult,1,-0.287511,1.371129,1,1,1
15,23366120,1,DE,CHOLECALCIFEROL | DESVENLAFAXINE | LORAZEPAM | POLYETHYLENE GLYCOL 3350\POTA...,1 | 2,CHOLECALCIFEROL | DESVENLAFAXINE | LORAZEPAM | MOVICOL | VALSARTAN,0.222358,female,68.0,801.0,elderly,0,0.379624,1.371129,1,1,0
16,23567582,2,JP,EPINASTINE | ESZOPICLONE | FAMOTIDINE | URSODIOL,1 | 2,EPINASTINE | FAMOTIDINE | LUNESTA | URSO,-0.048549,male,NaN,NaN,elderly,1,0.157246,1.371129,1,1,0
17,24803782,1,IT,BUSULFAN | CYCLOSPORINE | FLUDARABINE PHOSPHATE | METHOTREXATE,1,BUSULFAN | CYCLOSPORINE | FLUDARABINE | METHOTREXATE,0.132055,unknown,NaN,NaN,adult,1,0.157246,-0.721418,1,1,0
18,23680729,2,US,LUTETIUM LU-177 VIPIVOTIDE TETRAXETAN,1,PLUVICTO,-0.319456,unknown,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,1
19,24861952,1,CO,MYCOPHENOLIC ACID | TACROLIMUS,1,MYCOPHENOLIC ACID | TACROLIMUS,-0.138851,male,61.0,801.0,elderly,0,-0.287511,-0.721418,1,1,0

## 4. Dataset Depois - Teste Transformado

Este arquivo e o conjunto de teste final. Ele recebeu as transformacoes aprendidas no treino, sem ser usado para ajustar o KNN nem o StandardScaler.

In [14]:
test_df.head(20)

,safetyreportid,serious,occurcountry,patient.drug.activesubstance.activesubstancename,patient.drug.drugcharacterization,patient.drug.medicinalproduct,patient.drug.count,patient.patientsex,patient.patientonsetage,patient.patientonsetageunit,patient.ageGroupCalculated,patient.ageGroupCalculated_was_imputed,feature_n_active_substances,feature_n_drug_types,feature_has_medicinal_product,feature_multiple_drugs,feature_is_usa
0,21105266,1,US,DEXAMETHASONE | GABAPENTIN | IXAZOMIB CITRATE | LENALIDOMIDE | METOPROLOL TA...,1 | 2,DEXAMETHASONE | GABAPENTIN | METOPROLOL TARTRATE | NINLARO | POMALYST | REVL...,0.312660,male,NaN,NaN,elderly,1,0.602002,1.371129,1,1,1
1,19924417,1,CA,CORTISONE | METHOTREXATE | PREDNISONE | SECUKINUMAB | SULFASALAZINE,1 | 2,CORTISONE | COSENTYX | METHOTREXATE | PREDNISONE | SULFASALAZINE,0.132055,female,66.0,801.0,elderly,0,0.379624,1.371129,1,1,0
2,24803579,2,US,ACETAMINOPHEN\HYDROCODONE BITARTRATE | ACYCLOVIR | ASPIRIN | ATORVASTATIN CA...,1 | 2,ASPIRIN | BACTRIM DS | BENAZEPRIL HYDROCHLOROTHIAZIDE EG | CALCIUM CARBONATE...,1.305985,male,72.0,801.0,elderly,0,2.825784,1.371129,1,1,1
3,21226586,1,US,PENTOSAN POLYSULFATE SODIUM,1,ELMIRON,-0.229154,female,NaN,NaN,adult,1,-0.509889,-0.721418,1,1,1
4,23361930,1,US,DIGOXIN | METOPROLOL | RIVAROXABAN,1 | 2,DIGOXIN | METOPROLOL | XARELTO,-0.138851,male,66.0,801.0,elderly,0,-0.065132,1.371129,1,1,1
5,25021694,2,US,CYCLOSPORINE | DUPILUMAB,1 | 2,CYCLOSPORINE | DUPILUMAB,-0.229154,unknown,NaN,NaN,elderly,1,-0.287511,1.371129,1,1,1
6,23510194,2,US,SARILUMAB,1,KEVZARA,-0.319456,female,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,1
7,21508497,2,GB,SOMATROPIN,1,GENOTROPIN,-0.319456,unknown,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,0
8,24733179,1,US,ASCORBIC ACID | ASPIRIN | CHOLECALCIFEROL | CLINDAMYCIN | CRANBERRY | CYANOC...,1 | 2,ADULT MULTIVITAMIN | ASCORBIC ACID | ASPIRIN | CLARITIN | CLINDAMYCIN | CRAN...,2.299309,female,78.0,801.0,elderly,0,4.382431,1.371129,1,1,1
9,23611217,1,US,CYCLOSPORINE | MYCOPHENOLIC ACID,1,CYCLOSPORINE | MYCOPHENOLIC ACID,-0.229154,male,72.0,801.0,elderly,0,-0.287511,-0.721418,1,1,1
10,21897668,2,US,DUPILUMAB,1,DUPIXENT,-0.319456,male,NaN,NaN,adult,1,-0.509889,-0.721418,1,0,1
11,24808399,1,GB,LEVETIRACETAM,1,LEVETIRACETAM,-0.319456,male,7.0,801.0,child,0,-0.509889,-0.721418,1,0,0
12,22108481,1,MT,BIPERIDEN | CALCIUM POLYCARBOPHIL | CHLORPROMAZINE | DISTIGMINE BROMIDE | FL...,1 | 2,BIPERIDEN | CALCIUM POLYCARBOPHIL | CHLORPROMAZINE | DISTIGMINE BROMIDE | FL...,0.673869,unknown,NaN,NaN,adult,1,1.936271,1.371129,1,1,0
13,24807424,1,US,COCAINE | FENTANYL | METHAMPHETAMINE,1,COCAINE | FENTANYL | METHAMPHETAMINE,-0.138851,female,40.0,801.0,adult,0,-0.065132,-0.721418,1,1,1
14,21839165,2,US,DONEPEZIL HYDROCHLORIDE\MEMANTINE HYDROCHLORIDE,1,NAMZARIC,-0.319456,unknown,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,1
15,25057553,2,US,NALOXONE HYDROCHLORIDE,1,NALOXONE HYDROCHLORIDE,-0.319456,unknown,NaN,NaN,adult,1,-0.509889,-0.721418,1,0,1
16,21096380,1,CN,CYCLOSPORINE,1,CYCLOSPORINE,-0.229154,male,18.0,801.0,young_adult,0,-0.509889,-0.721418,1,1,0
17,21985796,2,US,TIRZEPATIDE,1,MOUNJARO,-0.229154,female,44.0,801.0,adult,0,-0.509889,-0.721418,1,1,1
18,24941278,1,US,HYDROCHLOROTHIAZIDE\LISINOPRIL | VOCLOSPORIN,1 | 2,LISINOPRIL AND HYDROCHLOROTHIAZIDE | LUPKYNIS,-0.229154,female,NaN,NaN,adult,1,-0.287511,1.371129,1,1,1
19,24954852,2,US,LENALIDOMIDE,1,LENALIDOMIDE,-0.319456,male,72.0,801.0,elderly,0,-0.509889,-0.721418,1,0,1

## 5. Amostra Para Entrega

Esta e a amostra recomendada para mostrar para a professora. Ela contem 25 registros do treino e 25 do teste, indicados pela coluna `split`.

In [15]:
sample_df.head(50)

,split,safetyreportid,serious,occurcountry,patient.drug.activesubstance.activesubstancename,patient.drug.drugcharacterization,patient.drug.medicinalproduct,patient.drug.count,patient.patientsex,patient.patientonsetage,patient.patientonsetageunit,patient.ageGroupCalculated,patient.ageGroupCalculated_was_imputed,feature_n_active_substances,feature_n_drug_types,feature_has_medicinal_product,feature_multiple_drugs,feature_is_usa
0,train,23530731,1,IN,AMLODIPINE BESYLATE | AZATHIOPRINE | MYCOPHENOLATE MOFETIL | PREDNISOLONE | ...,1 | 2,AMLODIPINE | AZATHIOPRINE | MYCOPHENOLATE MOFETIL | PREDNISOLONE | TACROLIMUS,0.041753,female,NaN,NaN,young_adult,1,0.379624,1.371129,1,1,0
1,train,23573794,1,US,ALFUZOSIN | APIXABAN | BENAZEPRIL HYDROCHLORIDE | CARBIDOPA\LEVODOPA | HYDRO...,1 | 2,ALFUZOSIN | BENAZEPRIL | BENICAR | CARBIDOPA\LEVODOPA | ELIQUIS | HYDROCHLOR...,0.944776,male,76.0,801.0,elderly,0,1.936271,1.371129,1,1,1
2,train,24801725,1,US,GILTERITINIB | POSACONAZOLE,1,GILTERITINIB | POSACONAZOLE,-0.229154,female,70.0,801.0,elderly,0,-0.287511,-0.721418,1,1,1
3,train,24830941,1,US,ALPRAZOLAM | FENTANYL | OXYCODONE,1,ALPRAZOLAM | FENTANYL | OXYCODONE,-0.138851,male,30.0,801.0,adult,0,-0.065132,-0.721418,1,1,1
4,train,21927215,1,US,ATORVASTATIN CALCIUM | EMPAGLIFLOZIN | LISINOPRIL | TIRZEPATIDE,1 | 2,JARDIANCE | LIPITOR | LISINOPRIL | MOUNJARO | TOJEO,0.132055,male,44.0,801.0,adult,0,0.157246,1.371129,1,1,1
5,train,21883320,2,US,SACUBITRIL\VALSARTAN,1,ENTRESTO,-0.319456,female,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,1
6,train,23678680,2,US,DENOSUMAB,1,PROLIA,-0.319456,unknown,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,1
7,train,22084593,1,FR,ACETAMINOPHEN | ALPRAZOLAM | PROPRANOLOL HYDROCHLORIDE,1 | 2,ACETAMINOPHEN | ALPRAZOLAM | PROPRANOLOL,-0.138851,female,43.0,801.0,adult,0,-0.065132,1.371129,1,1,0
8,train,21800099,2,US,ABATACEPT,1,ORENCIA,-0.229154,female,72.0,801.0,elderly,0,-0.509889,-0.721418,1,1,1
9,train,23409935,1,AU,BORTEZOMIB,1,BORTEZOMIB,-0.319456,male,69.0,801.0,elderly,0,-0.509889,-0.721418,1,0,0
10,train,24854567,1,FR,GLIMEPIRIDE | METFORMIN HYDROCHLORIDE | SPIRONOLACTONE | VILDAGLIPTIN,1,GLIMEPIRIDE | METFORMIN | SPIRONOLACTONE | VILDAGLIPTIN,-0.048549,unknown,NaN,NaN,elderly,1,0.157246,-0.721418,1,1,0
11,train,23552895,1,US,AMANTADINE | AMPHETAMINE ASPARTATE\AMPHETAMINE ASPARTATE MONOHYDRATE\AMPHETA...,1 | 2,"AMANTADINE | DEXTROAMPHET SACCHARAT, AMPHET ASPARTATE, DEXTROAMPHET SULFATE ...",0.041753,unknown,NaN,NaN,elderly,1,0.157246,1.371129,1,1,1
12,train,23387999,1,GB,ALLOPURINOL | FINASTERIDE,1 | 2,ALLOPURINOL | FINASTERIDE,-0.229154,male,49.0,801.0,adult,0,-0.287511,1.371129,1,1,0
13,train,21168322,1,AU,VEDOLIZUMAB,1,VEDOLIZUMAB,-0.229154,male,NaN,NaN,adult,1,-0.509889,-0.721418,1,1,0
14,train,20524604,2,US,SILDENAFIL CITRATE | TREPROSTINIL,1 | 2,SILDENAFIL CITRATE | TREPROSTINIL,-0.138851,female,NaN,NaN,adult,1,-0.287511,1.371129,1,1,1
15,train,23366120,1,DE,CHOLECALCIFEROL | DESVENLAFAXINE | LORAZEPAM | POLYETHYLENE GLYCOL 3350\POTA...,1 | 2,CHOLECALCIFEROL | DESVENLAFAXINE | LORAZEPAM | MOVICOL | VALSARTAN,0.222358,female,68.0,801.0,elderly,0,0.379624,1.371129,1,1,0
16,train,23567582,2,JP,EPINASTINE | ESZOPICLONE | FAMOTIDINE | URSODIOL,1 | 2,EPINASTINE | FAMOTIDINE | LUNESTA | URSO,-0.048549,male,NaN,NaN,elderly,1,0.157246,1.371129,1,1,0
17,train,24803782,1,IT,BUSULFAN | CYCLOSPORINE | FLUDARABINE PHOSPHATE | METHOTREXATE,1,BUSULFAN | CYCLOSPORINE | FLUDARABINE | METHOTREXATE,0.132055,unknown,NaN,NaN,adult,1,0.157246,-0.721418,1,1,0
18,train,23680729,2,US,LUTETIUM LU-177 VIPIVOTIDE TETRAXETAN,1,PLUVICTO,-0.319456,unknown,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,1
19,train,24861952,1,CO,MYCOPHENOLIC ACID | TACROLIMUS,1,MYCOPHENOLIC ACID | TACROLIMUS,-0.138851,male,61.0,801.0,elderly,0,-0.287511,-0.721418,1,1,0
20,train,23600146,1,JP,CARBOPLATIN | IPILIMUMAB | NIVOLUMAB | PACLITAXEL,1,CARBOPLATIN | IPILIMUMAB | NIVOLUMAB | PACLITAXEL,-0.048549,female,67.0,801.0,elderly,0,0.157246,-0.721418,1,1,0
21,train,22100833,1,US,RANITIDINE,1,RANITIDINE,-0.229154,unknown,NaN,NaN,elderly,1,-0.509889,-0.721418,1,1,1
22,train,19412336,1,CA,ALBUTEROL SULFATE | FLUTICASONE PROPIONATE\SALMETEROL XINAFOATE | MEPOLIZUMA...,1 | 2,ADVAIR HFA | ALBUTEROL SULFATE | NUCALA | PREDNISONE | SINGULAIR | TIOTROPIU...,0.402962,female,73.0,801.0,elderly,0,0.824380,1.371129,1,1,0
23,train,24884720,1,US,CLONIDINE,1,CLONIDINE,-0.229154,female,48.0,801.0,adult,0,-0.509889,-0.721418,1,1,1
24,train,24889366,1,US,DOCETAXEL | FLUOROURACIL | LEUCOVORIN\LEUCOVORIN CALCIUM | OXALIPLATIN,1,DOCETAXEL | FLUOROURACIL | LEUCOVORIN | OXALIPLATIN,-0.048549,male,67.0,801.0,elderly,0,0.157246,-0.721418,1,1,1
25,test,21105266,1,US,DEXAMETHASONE | GABAPENTIN | IXAZOMIB CITRATE | LENALIDOMIDE | METOPROLOL TA...,1 | 2,DEXAMETHASONE | GABAPENTIN | METOPROLOL TARTRATE | NINLARO | POMALYST | REVL...,0.312660,male,NaN,NaN,elderly,1,0.602002,1.371129,1,1,1
26,test,19924417,1,CA,CORTISONE | METHOTREXATE | PREDNISONE | SECUKINUMAB | SULFASALAZINE,1 | 2,CORTISONE | COSENTYX | METHOTREXATE | PREDNISONE | SULFASALAZINE,0.132055,female,66.0,801.0,elderly,0,0.379624,1.371129,1,1,0
27,test,24803579,2,US,ACETAMINOPHEN\HYDROCODONE BITARTRATE | ACYCLOVIR | ASPIRIN | ATORVASTATIN CA...,1 | 2,ASPIRIN | BACTRIM DS | BENAZEPRIL HYDROCHLOROTHIAZIDE EG | CALCIUM CARBONATE...,1.305985,male,72.0,801.0,elderly,0,2.825784,1.371129,1,1,1
28,test,21226586,1,US,PENTOSAN POLYSULFATE SODIUM,1,ELMIRON,-0.229154,female,NaN,NaN,adult,1,-0.509889,-0.721418,1,1,1
29,test,23361930,1,US,DIGOXIN | METOPROLOL | RIVAROXABAN,1 | 2,DIGOXIN | METOPROLOL | XARELTO,-0.138851,male,66.0,801.0,elderly,0,-0.065132,1.371129,1,1,1
30,test,25021694,2,US,CYCLOSPORINE | DUPILUMAB,1 | 2,CYCLOSPORINE | DUPILUMAB,-0.229154,unknown,NaN,NaN,elderly,1,-0.287511,1.371129,1,1,1
31,test,23510194,2,US,SARILUMAB,1,KEVZARA,-0.319456,female,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,1
32,test,21508497,2,GB,SOMATROPIN,1,GENOTROPIN,-0.319456,unknown,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,0
33,test,24733179,1,US,ASCORBIC ACID | ASPIRIN | CHOLECALCIFEROL | CLINDAMYCIN | CRANBERRY | CYANOC...,1 | 2,ADULT MULTIVITAMIN | ASCORBIC ACID | ASPIRIN | CLARITIN | CLINDAMYCIN | CRAN...,2.299309,female,78.0,801.0,elderly,0,4.382431,1.371129,1,1,1
34,test,23611217,1,US,CYCLOSPORINE | MYCOPHENOLIC ACID,1,CYCLOSPORINE | MYCOPHENOLIC ACID,-0.229154,male,72.0,801.0,elderly,0,-0.287511,-0.721418,1,1,1
35,test,21897668,2,US,DUPILUMAB,1,DUPIXENT,-0.319456,male,NaN,NaN,adult,1,-0.509889,-0.721418,1,0,1
36,test,24808399,1,GB,LEVETIRACETAM,1,LEVETIRACETAM,-0.319456,male,7.0,801.0,child,0,-0.509889,-0.721418,1,0,0
37,test,22108481,1,MT,BIPERIDEN | CALCIUM POLYCARBOPHIL | CHLORPROMAZINE | DISTIGMINE BROMIDE | FL...,1 | 2,BIPERIDEN | CALCIUM POLYCARBOPHIL | CHLORPROMAZINE | DISTIGMINE BROMIDE | FL...,0.673869,unknown,NaN,NaN,adult,1,1.936271,1.371129,1,1,0
38,test,24807424,1,US,COCAINE | FENTANYL | METHAMPHETAMINE,1,COCAINE | FENTANYL | METHAMPHETAMINE,-0.138851,female,40.0,801.0,adult,0,-0.065132,-0.721418,1,1,1
39,test,21839165,2,US,DONEPEZIL HYDROCHLORIDE\MEMANTINE HYDROCHLORIDE,1,NAMZARIC,-0.319456,unknown,NaN,NaN,elderly,1,-0.509889,-0.721418,1,0,1
40,test,25057553,2,US,NALOXONE HYDROCHLORIDE,1,NALOXONE HYDROCHLORIDE,-0.319456,unknown,NaN,NaN,adult,1,-0.509889,-0.721418,1,0,1
41,test,21096380,1,CN,CYCLOSPORINE,1,CYCLOSPORINE,-0.229154,male,18.0,801.0,young_adult,0,-0.509889,-0.721418,1,1,0
42,test,21985796,2,US,TIRZEPATIDE,1,MOUNJARO,-0.229154,female,44.0,801.0,adult,0,-0.509889,-0.721418,1,1,1
43,test,24941278,1,US,HYDROCHLOROTHIAZIDE\LISINOPRIL | VOCLOSPORIN,1 | 2,LISINOPRIL AND HYDROCHLOROTHIAZIDE | LUPKYNIS,-0.229154,female,NaN,NaN,adult,1,-0.287511,1.371129,1,1,1
44,test,24954852,2,US,LENALIDOMIDE,1,LENALIDOMIDE,-0.319456,male,72.0,801.0,elderly,0,-0.509889,-0.721418,1,0,1
45,test,23578687,1,IT,EVEROLIMUS | EXEMESTANE | LETROZOLE | PALBOCICLIB | VINORELBINE TARTRATE,1,EVEROLIMUS | EXEMESTANE | LETROZOLE | PALBOCICLIB | VINORELBINE,0.312660,female,61.0,801.0,elderly,0,0.379624,-0.721418,1,1,0
46,test,24941195,1,CN,ASPARAGINASE | DOXORUBICIN | ETOPOSIDE | IFOSFAMIDE | METHOTREXATE | METHYLP...,1,ASPARAGINASE | DOXORUBICIN | ETOPOSIDE | IFOSFAMIDE | METHOTREXATE | METHYLP...,0.222358,male,NaN,NaN,young_adult,1,0.824380,-0.721418,1,1,0
47,test,24924588,2,US,CABOZANTINIB S-MALATE,1,CABOMETYX,-0.319456,male,NaN,NaN,adult,1,-0.509889,-0.721418,1,0,1
48,test,21102852,2,US,CYCLOSPORINE | MYCOPHENOLATE SODIUM,1,MYFORTIC | NEORAL,-0.229154,female,NaN,NaN,elderly,1,-0.287511,-0.721418,1,1,1
49,test,24664002,1,US,CERTOLIZUMAB PEGOL | PREDNISONE,1 | 2,CIMZIA | PREDNISONE,-0.229154,female,NaN,NaN,adult,1,-0.287511,1.371129,1,1,1

## 6. Comparacao de Colunas Antes e Depois

In [16]:
comparison = pd.DataFrame({
    'antes_cleaned': pd.Series(cleaned_df.columns),
    'depois_train_test': pd.Series(train_df.columns),
})
comparison

                                       antes_cleaned                                 depois_train_test
0                                     safetyreportid                                    safetyreportid
1                                            serious                                           serious
2                                       occurcountry                                      occurcountry
3   patient.drug.activesubstance.activesubstancename  patient.drug.activesubstance.activesubstancename
4                  patient.drug.drugcharacterization                 patient.drug.drugcharacterization
5                      patient.drug.medicinalproduct                     patient.drug.medicinalproduct
6                                 patient.drug.count                                patient.drug.count
7                                 patient.patientsex                                patient.patientsex
8                            patient.patientonsetage                           patient.patientonsetage
9                        patient.patientonsetageunit                       patient.patientonsetageunit
10                        patient.ageGroupCalculated                        patient.ageGroupCalculated
11            patient.ageGroupCalculated_was_imputed            patient.ageGroupCalculated_was_imputed
12                                               NaN                       feature_n_active_substances
13                                               NaN                              feature_n_drug_types
14                                               NaN                     feature_has_medicinal_product
15                                               NaN                            feature_multiple_drugs
16                                               NaN                                    feature_is_usa

## 7. Resumo dos Dados Gerados

In [17]:
summary = pd.DataFrame([
    {
        'arquivo': 'drug_events_cleaned.csv',
        'papel': 'base limpa antes da nova transformacao',
        'registros': len(cleaned_df),
        'colunas': cleaned_df.shape[1],
    },
    {
        'arquivo': 'drug_events_train_transformed.csv',
        'papel': 'treino depois da transformacao',
        'registros': len(train_df),
        'colunas': train_df.shape[1],
    },
    {
        'arquivo': 'drug_events_test_transformed.csv',
        'papel': 'teste depois da transformacao',
        'registros': len(test_df),
        'colunas': test_df.shape[1],
    },
    {
        'arquivo': 'drug_events_sample.csv',
        'papel': 'amostra visual para conferencia',
        'registros': len(sample_df),
        'colunas': sample_df.shape[1],
    },
])
summary

                             arquivo                                   papel  registros  colunas
0            drug_events_cleaned.csv  base limpa antes da nova transformacao      32309       12
1  drug_events_train_transformed.csv          treino depois da transformacao      22616       17
2   drug_events_test_transformed.csv           teste depois da transformacao       9693       17
3             drug_events_sample.csv         amostra visual para conferencia         50       18

## 8. Metadata: Parametros Salvos

A professora pediu que, na normalizacao, o conjunto de treino fosse normalizado, os parametros fossem gravados e depois aplicados no teste.

O arquivo `data_preparation_metadata.json` e justamente a evidencia disso: ele registra as medias e desvios aprendidos no treino, alem de informar que o KNN e o StandardScaler foram ajustados apenas com dados de treinamento.

In [18]:
scaler_params = metadata['scaler_parameters']
scaler_df = pd.DataFrame({
    'feature': scaler_params['features'],
    'media_aprendida_no_treino': scaler_params['mean'],
    'desvio_aprendido_no_treino': scaler_params['scale'],
})
scaler_df

                       feature  media_aprendida_no_treino  desvio_aprendido_no_treino
0           patient.drug.count                   4.537628                   11.073923
1  feature_n_active_substances                   3.292890                    4.496844
2         feature_n_drug_types                   1.344756                    0.477886

## 9. Metadata: Imputacao KNN e Split

In [19]:
knn_info = metadata['age_group_imputation']
knn_summary = pd.DataFrame([
    {'item': 'metodo', 'valor': knn_info['method']},
    {'item': 'escopo do ajuste', 'valor': knn_info['fit_scope']},
    {'item': 'alvo imputado', 'valor': knn_info['target']},
    {'item': 'registros imputados no treino', 'valor': knn_info['train_imputed_records']},
    {'item': 'registros imputados no teste', 'valor': knn_info['test_imputed_records']},
])
knn_summary

                            item                       valor
0                         metodo                  KNNImputer
1               escopo do ajuste           training set only
2                  alvo imputado  patient.ageGroupCalculated
3  registros imputados no treino                        8945
4   registros imputados no teste                        3781

## 10. Distribuicao da Variavel Alvo

In [20]:
target_distribution = pd.DataFrame({
    'treino': train_df['serious'].value_counts().sort_index(),
    'teste': test_df['serious'].value_counts().sort_index(),
})
target_distribution['treino_%'] = (target_distribution['treino'] / len(train_df) * 100).round(2)
target_distribution['teste_%'] = (target_distribution['teste'] / len(test_df) * 100).round(2)
target_distribution

   treino  teste  treino_%  teste_%
1   14089   6039      62.3     62.3
2    8527   3654      37.7     37.7

## 11. Conferencia da Normalizacao

In [21]:
normalized_features = metadata['dataset_info']['numeric_features_normalized']
normalization_check = pd.concat(
    {
        'treino_media': train_df[normalized_features].mean(),
        'treino_desvio': train_df[normalized_features].std(),
        'teste_media': test_df[normalized_features].mean(),
        'teste_desvio': test_df[normalized_features].std(),
    },
    axis=1,
)
normalization_check

                             treino_media  treino_desvio  teste_media  teste_desvio
patient.drug.count           1.005366e-17       1.000022    -0.006505      0.886765
feature_n_active_substances  6.409211e-17       1.000022    -0.002707      1.002404
feature_n_drug_types         1.558318e-16       1.000022    -0.000155      1.000453